
# ideally database username/pwd to be read from application.yml and loaded by figaro
# but hard-coded for this demo

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000